#!/bin/bash
# Script to update commit info header before committing

COMMIT_HASH=$(git log -1 --format=%h)
COMMIT_MSG=$(git log -1 --format=%s)

# Truncate to 14 characters
COMMIT_MSG_TRUNCATED=$(echo "$COMMIT_MSG" | cut -c1-14)

# Split into 7-character lines
LINE1=$(echo "$COMMIT_MSG_TRUNCATED" | cut -c1-7)
LINE2=$(echo "$COMMIT_MSG_TRUNCATED" | cut -c8-14)

# Pad LINE2 if it's shorter than expected (for cleaner display)
if [ -z "$LINE2" ]; then
    LINE2=""
fi

HEADER_FILE="boards/shields/nice_view_disp/widgets/commit_info.h"

cat > "$HEADER_FILE" << EOF
/*
 * Copyright (c) 2023 The ZMK Contributors
 * SPDX-License-Identifier: MIT
 *
 * Auto-generated file - DO NOT EDIT MANUALLY
 * Generated by update-commit-info.sh
 * Commit: ${COMMIT_HASH} - ${COMMIT_MSG}
 */

#pragma once

#define GIT_COMMIT_HASH "${COMMIT_HASH}"
#define GIT_COMMIT_MSG_LINE1 "${LINE1}"
#define GIT_COMMIT_MSG_LINE2 "${LINE2}"
EOF

echo "Updated commit info: ${COMMIT_HASH} - ${COMMIT_MSG}"
echo "  Line 1: '${LINE1}'"
echo "  Line 2: '${LINE2}'"
