/*
 * Copyright (c) 2023 The ZMK Contributors
 * SPDX-License-Identifier: MIT
 *
 * Auto-generated file - DO NOT EDIT MANUALLY
 * Generated by update-commit-info.sh
 * Commit: 3227999 - feat: display smaller but twice as many characters
 */

#pragma once

#define GIT_COMMIT_HASH "3227999"
#define GIT_COMMIT_MSG_LINE1 "feat: display "
#define GIT_COMMIT_MSG_LINE2 "smaller but tw"
