/*
 * Copyright (c) 2023 The ZMK Contributors
 * SPDX-License-Identifier: MIT
 *
 * Auto-generated file - DO NOT EDIT MANUALLY
 * Generated by update-commit-info.sh
 * Commit: 3c89b88 - feat: switch to hold-prefered.
 */

#pragma once

#define GIT_COMMIT_HASH "3c89b88"
#define GIT_COMMIT_MSG_LINE1 "feat: s"
#define GIT_COMMIT_MSG_LINE2 "witch t"
