/*
 * Copyright (c) 2023 The ZMK Contributors
 * SPDX-License-Identifier: MIT
 *
 * Auto-generated file - DO NOT EDIT MANUALLY
 * Generated by update-commit-info.sh
 * Commit: 079779d - fix: revert to 8 px font
 */

#pragma once

#define GIT_COMMIT_HASH "079779d"
#define GIT_COMMIT_MSG_LINE1 "fix: re"
#define GIT_COMMIT_MSG_LINE2 "vert to"
